model_params:
  colsample_bytree: 0.8
  eval_metric: logloss
  learning_rate: 0.1
  max_depth: 6
  n_estimators: 200
  n_jobs: -1
  objective: binary:logistic
  random_state: 42
  subsample: 0.8
n_features: 52
training_date: '2025-07-27T22:32:01.553125'
training_months: 12
